CREATE TABLE AUTHOR (
    AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(20)
);
create table books (
    book_id int PRIMARY KEY,
    title varchar(100),
    author_ID INT,
    FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
    );
 
INSERT INTO AUTHOR VALUES(1,"SUJATHA"),(2,"PUDHUMAI PITHAN"),(3,"JEYAMOHAN");

INSERT INTO BOOKS VALUES(101,"ENDHIRAN",1),(102,"KAANCHANAI",2),(103,"AZHAGI",3);

select title from books;

UPDATE AUTHOR SET AUTHOR_NAME="MAARAN" WHERE AUTHOR_ID=3;




UPDATE AUTHOR SET AUTHOR_NAME="AMARAN" WHERE AUTHOR_ID=(SELECT AUTHOR_ID FROM BOOKS WHERE(BOOK_ID=102));

DELETE FROM BOOKS WHERE AUTHOR_ID=2;
DELETE FROM AUTHOR WHERE AUTHOR_ID=2;

INSERT INTO BOOKS VALUES(104,"1982",2),(105,"ARAM",1),(106,"MANIDHI",3);

INSERT INTO AUTHOR VALUES(4,"JAYABALAN");

SELECT TITLE,AUTHOR_NAME FROM BOOKS RIGHT JOIN AUTHOR ON BOOKS.AUTHOR_ID=AUTHOR.AUTHOR_ID;
SELECT TITLE,AUTHOR_NAME FROM BOOKS LEFT JOIN AUTHOR ON BOOKS.AUTHOR_ID=AUTHOR.AUTHOR_ID;

SELECT AUTHOR.AUTHOR_NAME, BOOKS.title 
FROM BOOKS 
full JOIN AUTHOR ON BOOKS.author_ID = AUTHOR.AUTHOR_ID;


